name: fix code styling

on:
  workflow_call:
    inputs:
      php:
        default: "8.5"
        type: string
      message:
        default: "refactor: php-cs-fixer"
        type: string
      fix:
        default: true
        type: boolean
    secrets:
      COMPOSER_AUTH:
        required: true
        description: A base64-encoded string containing the composer auth.json file contents.
jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Add Composer HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json

      - run: composer install
      - run: composer update
      - name: Install socoladaica/laravel-audit
        run: composer require socoladaica/laravel-audit:12.0 --dev
        if: ${{ github.repository != 'SocolarDaiCa/laravel-audit' }}

      - name: Run php-cs-fixer
        run: $GITHUB_WORKSPACE/vendor/bin/php-cs-fixer --config=$GITHUB_WORKSPACE/.php_cs.php fix
        if: ${{ github.repository == 'SocolarDaiCa/laravel-audit' }}

      - name: Run php-cs-fixer
        run: $GITHUB_WORKSPACE/vendor/bin/php-cs-fixer --config=$GITHUB_WORKSPACE/vendor/socoladaica/laravel-audit/.php_cs.php fix
        if: ${{ github.repository != 'SocolarDaiCa/laravel-audit' }}

      - name: Reset some uncommitted changes
        run: git checkout -- composer.json

      - name: Commit linted files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.message }}
