name: Review code

on:
  workflow_call:
    inputs:
      php:
        default: "8.5"
        type: string
#      message:
#        default: "refactor: php-cs-fixer"
#        type: string
#      fix:
#        default: true
#        type: boolean
    secrets:
      COMPOSER_AUTH:
        required: true
        description: A base64-encoded string containing the composer auth.json file contents.
jobs:
  review-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Add Composer HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json

      - run: composer install
      - name: Install socoladaica/laravel-audit
        run: composer require socoladaica/laravel-audit:12.0 --dev
        if: ${{ github.repository != 'SocolarDaiCa/laravel-audit' }}

      - name: Run larastan
        run: $GITHUB_WORKSPACE/vendor/bin/phpstan analyse -c $GITHUB_WORKSPACE/audit.neon
        if: ${{ github.repository == 'SocolarDaiCa/laravel-audit' }}

      - name: Run larastan
        run: $GITHUB_WORKSPACE/vendor/bin/phpstan analyse -c $GITHUB_WORKSPACE/vendor/socoladaica/laravel-audit/audit-package.neon
        if: ${{ github.repository != 'SocolarDaiCa/laravel-audit' }}
